name = input("whats your name:")
age = input("whats your age? ")
job = input("whats your job? ")
language = input("whats your fav programming language? ")
print("\n-------my profile--------")
print("my name is ", name)
print("i am ", age , "years old")
print("i am", job)
print("i like ", language, " too much")
